[workspace]
resolver = "2"
members = [
  "srcs/html2md-example",
  "srcs/cli-test",
  "srcs/hello_rust",
  "courses/kiskoz-30days/day2",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT"

# rust-version = "1.68"
[profile.dev]
