baseURL = "https://gtrunsec.github.io/learning-rust-roadmap"
languageCode = "en-us"
title = "My Roadmap to Learning Rust"
theme = "cortex"
[params]
email = "jethrokuan95@gmail.com"
footer = "Icon by Freepik. Built with ♥ with Org-mode and Hugo."

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = "4"
