name: "CI"
on:
  pull_request:
  push:
jobs:
  nix-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v16
      with:
        install_url:
          https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.6.0pre20220106_f71d846/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix

    - name: Nix Flake Check
      run: nix -Lv flake check
