name: "CI"
on:
  pull_request:
  push:
jobs:
  nix-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v22
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: clippy linting
        run: nix develop -c lint
