name: "CI"
on:
  pull_request:
  push:
jobs:
  nix-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v14.1
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix

    - uses: actions/cache@v2.1.5
      with:
        path: |
          path: /nix/store
        key: ${{ matrix.os }}-nix-store


    # CI workflows
    - name: Nix Format Check
      run: nix -Lv develop -c nixpkgs-fmt --check .
    - name: Do not check python
      run: |
        sed -i 's| python-packages-custom #comment|\#python-packages-custom #comment|' flake.nix
    - name: Nix Flake Check
      run: nix -Lv flake check
